import { stage as _foundry } from './foundry.js';
import { stage as _orbital } from './orbital.js';
import { stage as _scrapyard } from './scrapyard.js';
import { stage as _neoncity } from './neoncity.js';
import { stage as _arctic } from './arctic.js';
import { stage as _cloudtemple } from './cloudtemple.js';
import { stage as _moltencore } from './moltencore.js';
import { stage as _datarealm } from './datarealm.js';
import { stage as _carnival } from './carnival.js';
import { stage as _jungle } from './jungle.js';
import { stage as _skytemple } from './skytemple.js';
import { stage as _neocity2 } from './neocity2.js';
export const STAGES = [_foundry, _orbital, _scrapyard, _neoncity, _arctic, _cloudtemple, _moltencore, _datarealm, _carnival, _jungle, _skytemple, _neocity2];
export { drawStageBG, drawStageGeom, drawFerrisWheel, drawJungleTrees, drawNeoBuildings, drawGear } from './drawStageBG.js';
